[build]
  command = "npm run build"
  publish = "dist"

# Custom 404 pages per language
[[redirects]]
  from = "/en/*"
  to = "/en/404/index.html"
  status = 404

[[redirects]]
  from = "/ru/*"
  to = "/ru/404/index.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
